title: Hankun Dai
position: Undergraduate Student
affiliation: University of Chinese Academy of Sciences
email: daihankun19@mails.ucas.ac.cn
keywords: minimal academic
github_link: https://github.com/d-hank
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: DHank's homepage
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
